server:
  servlet:
    context-path: /springboot
  port: 8088

spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&userSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver